version: '3.8'

services:
  backend:
    build:
      context: ./backend
    container_name: fastapi_backend
    environment:
      DATABASE_URL: postgresql://admin:admin@db:5432/blog_db
    ports:
      - "8000:8000"
    depends_on:
      db:
        condition: service_healthy
    volumes:
      - ./backend/alembic:/app/alembic

  db:
    image: postgres:15
    container_name: postgres_db
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
      POSTGRES_DB: blog_db
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U admin -d blog_db"]
      interval: 5s
      timeout: 5s
      retries: 5

volumes:
  postgres_data:
